var allQuestions = [
  {question: "1. Ronald has been working on his new graphics for a CD cover. He spent 2 hours and 10 minutes on the design. How many minutes did he spend completing the design?",
    value: "20",
    answers: ["150", "20", "130"],
    correctAnswer: 3},
  {question: "2. Charlene just made $3,400.00 filming a Teyonce interview. Teyonce's manager paid Charlene in all $100 dollar bills. How many 100 dollar bills did Charlene have in her purse? ",
    value: "20",
    answers: ["34,000", "340,000", "34"],
    correctAnswer: 3},
  {question: "3.Trizzy Beats makes 3 beats per day for 7 days. The next week she makes 5 beats per day for 3 days. She deletes 4 from her hard drive by mistake. How many beats does she have after the two weeks production? ",
    value: "40",
    answers: ["32", "15", "21"],
    correctAnswer: 1},
  {question: "4.Young Pov gets an offer to use one of his songs in a video game. He will receive a royalty of 10% of the $50 video game.  If 50,000 games are sold in the USA, how much will Young Pov make from the deal?",
    value: "70",
    answers: ["$350,000", "$250,000", "$200,000", "$100,000"],
    correctAnswer: 2},
  {question: "5. The Rapper named Puller T gets an offer to sign with the independent record label  Def Beats. He is given an offer of a $300,000 advance recording budget for 2 albums for 3 years.  With this budget he needs to cover the production expenses of $50,000 to create 10 tracks for both albums, pay the engineer $50,000 to record, mix and master the project, $100,000 for the video budget, and $30,000 for promotions and marketing. What will be the balance of the budget post payment of the services rendered? ",
    value: "100",
    answers: ["$80,000", "$70,000", "$90,000", "$60,000"],
    correctAnswer: 2},
  {question: "6. Puller T spent 4/9 of his budget on shopping and food during his tour. What fraction of his budget does he have left?",
    value: "30",
    answers: ["5/9", "6/9", "3/9", "7/9"],
    correctAnswer: 1},
  {question: "7. Production Team Skillz and Imahj go into business together for a production company called S.N.I. productions.  They both agreed to receive a 50/50 split from any royalties of published material.  How much would they each receive from a payment of $20,000 per track for a 5 song deal?",
    value: "20",
    answers: ["$60,000", "$70,000", "$50,000", "$40,000"],
    correctAnswer: 3},
  {question: "8. If Big Butta averages four sales of his $10.00 CD for every 50,000 views on his video, what is the projected sales if he reaches 300,000 views? ",
    value: "50",
    answers: ["$240", "$360", "$420"],
    correctAnswer: 1},
  {question: "9. Big Wayne just signed a record deal that takes 20% of everything he makes from his brand (music, clothes, appreances etc.)  Big Wayne and his friends have been working on a T-Shirt design for 10 years prior to him signing. They decide to sale the shirt for $10. If Big Wayne sales 100,000 shirts, what is the labels cut?",
    value: "100",
    answers: ["$200,000", "$1,000,000", "$20,000"],
    correctAnswer: 1},
  {question: "10. Big Butta enters a beat battle (music producer competition). Where in front of a crowd and judges he plays an original instrumental and competes against other beat makers. The prize consists of a combination of the producers $25 registration fee used to enter the battle. With 15 producers competing, what is the total prize amount for the winner?",
    value: "50",
    answers: ["$250", "$475", "$375"],
    correctAnswer: 3},
  {question: "11. Maurice is collecting signatures from the people in his building. He needs permission from the residents to film a music video on Saturday inside the building. There are 3 floors with 4 apartments on each floor. Maurice receives  2 signatures from every home. How many signatures will he total if all residents sign?",
    value: "100",
    answers: ["35", "24", "7"],
    correctAnswer: 2},
  {question: "12.Jackie had a starting budget of $345.99. She paid $77.00 for business cards and paid $165.00 for a trip to New York to promote her web business. Her website brought in $550.00 of sales over the next week. What is her remaining balance of the budget?",
    value: "50",
    answers: ["$477", "$234.99", "653.99"],
    correctAnswer: 3},
  {question: "13. Young Pov gets an offer to use one of his songs in a video game sound track. For this use he will receive a royalty payment of 10% of the retail price of $50.00 for the video game.  If 50,000 games are sold in the USA, how much will Young Pov make from the deal?",
    value: "80",
    answers: ["$350,000", "$250,000", "$200,000", "$100,000"],
    correctAnswer: 2},
  {question: "14. Synergy just produced a hit record for the artist Young Pov and the song has hit number one on the Itunes sales charts. The record has sold a total of 360,000 units in one 30 day month.  How many units per day does that average out to be?",
    value: "70",
    answers: ["113 Units", "986 Units", "14,000 Units", "12,000 Units"],
    correctAnswer: 4}
]

var imgs = [
  'img/01Workspace.png',
  'img/02Workspace.png',
  'img/03Workspace.png',
  'img/04Workspace.png',
  'img/05Workspace.png',
  'img/06Workspace.png',
  'img/07Workspace.png',
  'img/08Workspace.png',
  'img/10-vocal-workspace.png',
  'img/11-vocal-workspace.png',
  'img/12-vocal-workspace.png'
]

var audios = [
  {url: 'audio/01combo-drumbreak.mp3',
  value: 20},
  {url: 'audio/02combo-drumbreak-bass.mp3',
  value: 70},
  {url: 'audio/03combo-drumbreak-bass-snare.mp3',
  value: 50},
  {url: 'audio/04combo-drumbreak-bass-snare-hihat.mp3',
  value: 40},
  {url: 'audio/05combo-drumbreak-bass-snare-hihat-synth.mp3',
  value: 30},
  {url: 'audio/06combo-drumbreak-bass-snare-hihat-synth-sample.mp3',
  value: 40},
  {url: 'audio/07combo-drumbreak-bass-snare-hihat-synth-sample-kick.mp3',
  value: 50},
  {url: 'audio/08combo-drumbreak-bass-snare-hihat-synth-sample-kick-horn.mp3',
  value: 30}
]
